### ISSUE TITLE
Unable to trackexceptions

### ISSUE THREAD

**Issue by ferodom** [microsoft/ApplicationInsights-JS#1416]
I keep getting this error when I am trying to log an exception form JS.

I am initializing using the latest JS snippet, from this site, here is what I am using to track  appInsights.trackException(ex)

Error: not_specified
    at Si.sendExceptionInternal (https://js.monitor.azure.com/scripts/b/ai.2.min.js:5:66036)
    at Si.trackException (https://js.monitor.azure.com/scripts/b/ai.2.min.js:5:66256)
    at Object.sa.trackException (https://js.monitor.azure.com/scripts/b/ai.2.min.js:5:121388)
    at https://azapp-bswagentasnap-dev.azurewebsites.net/bswhp/CTID365.js:405:25
    at n.emit (https://azapp-bswagentasnap-dev.azurewebsites.net/bswhp/snap.min.js:1:352571)
    at w (https://azapp-bswagentasnap-dev.azurewebsites.net/bswhp/snap.min.js:1:696136)
    at I (https://azapp-bswagentasnap-dev.azurewebsites.net/bswhp/snap.min.js:1:697703)

**Comment by MSNev** [comment]
Hi @ferodom, how are you passing the exception down to the trackException call?

It should be wrapped as an object 
ai.trackException({
    exception: new Error("The Error")
});

The interface for this object is located here https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCommon/src/Interfaces/IExceptionTelemetry.ts#L12

**Comment by ferodom** [comment]
thanks for the response, I figured it out after I looked at the interface
