### ISSUE TITLE
Unable to test functional component in jest/enzyme using useTrackMetric hook 

### ISSUE THREAD

**Issue by ps-selliott** [microsoft/ApplicationInsights-JS#1437]
**Issue:** When using `useTrackMetric` hook within functional component, it renders fine in development but throws _"Invalid hook call. Hooks can only be called inside of the body of a function component."_ when trying to render in a jest/enzyme unit test. 

Stack trace appears to be pointing at the use of `useRef()` within `useComponentTracking` although I can't seem to figure out what hook rule is being broken. 

```
at useRef (node_modules\@microsoft\applicationinsights-react-js\node_modules\react\cjs\react.development.js:1504:20)
at useComponentTracking (node_modules\@microsoft\applicationinsights-react-js\dist-esm\useTrackMetric.js:11:20
at _default (...\SimpleComponent.js:6:32)
```

I was able to repro in my local environment with the code posted below, though I'm hoping this doesn't boil down to some kind of version resolution issue on my end. 

**Functional Component**
```
//SimpleComponent.js

import React from 'react';
import { ReactPlugin, useTrackMetric } from "@microsoft/applicationinsights-react-js";

export default function() {
    const aiPlugin = new ReactPlugin();
    const metricTrackingHook = useTrackMetric(aiPlugin, "Test");

    return (
        <div>
            <ul onMouseEnter={metricTrackingHook}>
                <li>Test</li>
            </ul>
        </div>
    )
}
```

**Unit Test**
```
//SimpleComponentTest.test.js

import React from 'react';
import { render } from '@testing-library/react';
import { mount } from "enzyme";
import SimpleComponent from "./SimpleComponent";

describe('SimpleComponentTest', () => {
    it('SimpleComponent engaged onMouseEnter', () => {
        // arrange

        // both render() and mount() return same hook error

        // let rtlRender = render(<SimpleComponent />)
        let enzMount = mount(<SimpleComponent />)

        // act
        // assert

    });
});
```

**Expected Behavior:** Functional Component renders without error.

**Relevant Dependency Versions:**
```
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "@microsoft/applicationinsights-react-js": "^3.0.5",
    "@microsoft/applicationinsights-web": "^2.5.10"

  "devDependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^10.4.9"
    "axios-mock-adapter": "^1.18.1",
    "babel-jest": "^24.9.0",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "enzyme-to-json": "^3.4.4",
    "jest": "^24.9.0",
    "jest-environment-jsdom-sixteen": "^1.0.3"
  }
```

Any insight into this is extremely appreciated. Thank you

**Comment by ps-selliott** [comment]
Update: Spent some time over the holiday break trying to reproduce this issue in codesandbox. 

I was able to get a working example in codesandbox pretty quickly, and was also able to get a second working example built off of the `create-react-app` codesandbox template. 

Because our current app uses `create-react-app`, I still have a feeling that might be causing issues somehow, even considering the possibility of 2 instances of `React` running with the same version. Oddly enough, this hook error only happens when trying to unit test a component using this custom hook, and does not actually occur in a production run.  

Things to note:
1. Tried the suggested `window.React1 === window.React2` for `react` and `react-dom` in several modules, all returning `true`. 
2. `npm ls react` and `npm ls react-dom` report 1 instance of each module, both with the same version. 
3. I am able to successfully test a default `React` hook, such as `React.useState` within my `SimpleComponent` without issue, this issue seems scoped more towards testing a custom hook from a third party plugin. 
4. Stepping through with a debugger; it appears  when we eventually reach `useComponentTracking`'s invocation of `useRef` `react.development.js.resolveDispatcher()` is showing null for `ReactCurrentDispatcher`, which ultimately triggers the "Invalid hook call" error. Wondering if this means `React` doesn't know what functional component invoked `useRef()`, or if this could somehow infer that my `SimpleComponent` is being rendered with 1 instance of `React`, while `useRef` is being invoked on another instance of `React`? 

Happy to provide any future updates, should I find a fix/workaround to this issue, but at this point I have run out of ideas on how to successfully unit test components using these custom hooks, within the scope of our app.

**Comment by ps-selliott** [comment]
**Update:** After further digging, it appears the issue is coming from an instance of `react` integrated within `dist/applicationinsights-react-js.js`, causing my `jest test` to fail since there are 2 different instances of `react`. 

**Issue:** 
When running `jest test SimpleComponentTest.test.js`, my `SimpleComponent` uses the `useComponentTracking` hook, which invokes `useRef()`, which then invokes `resolveDispatcher()` ultimately throwing an "invalid hook error" as `ReactCurrentDispatcher` is mysteriously null. After further debugging, it appears the react-based functions are being invoked witihn the scope of `dist/applicationinsights-react-js.js`,  as opposed to `node_modules/react`. I think this explains why `ReactCurrentDispatcher` is null, as there are 2 instances of `react` at play. 

I'm confused how `dist/applicationinsights-react-js.js` ends up with its own instance of `react`, which essentially leaves me with 2 `react` instances (violates hook rule: 3) when testing via `jest` (`enzyme` as well). 

**Questions:**
1. With `react` being listed as a `peerDependency` is it expected that `dist/applicationinsights-react-js.js` has its own instance of `react` integrated within? 
    - It's important to note, the `react` instance integrated within `dist/...` is the same version of `react` used by my app (which makes sense due to peerDependency). 

2. Are there any recommendations on how to successfully unit test components that use these custom hooks, such as `useComponentTracking`? 
    - My only option this point, is to possibly look into something like `jest-puppeteer` to emulate a browser environment when testing. 

**Additional Notes:**

This issue doesn't seem to happen when running in a browser, as everything behaves as expected. In fact, if I change the `main` key in `applicationinsights-react-js/package.json` to use `dist-esm/application...` instead of `dist/application...`, my jest test execution complains about the use of `import` as the files in `dist-esm` are obviously not transpiled (as expected). If I quickly update my jest config, I can have the files in `dist-esm` transpiled before test execution, which results in a passing test in which calls to `useRef()` and `resolveDispatcher()` are now being invoked from the true `node_modules/react` instance, where we have an established `ReactCurrentDispatcher`. 


Likewise, if I update the `module` key in `applicationinsights-react-js/package.json` to use `dist/application...` instead of `dist-esm/application...`, the browser based execution also returns the same "invalid hook error", likely due to the fact that `dist/applicationinsights-react-js.js` is invoking react-based functions from within itself, instead of the functions being invoked within `node_modules/react`.

Unfortunately, I know very little about webpack, but my hunch is running in a `web` environment ultimately uses `dist-esm` files (as per the `module` key in `package.json`), whereas running a `jest test` uses `dist` files (as per the `main` key in `package.json`), which somehow have the aforementioned integrated version of `react`. 

Any insight into this would be greatly appreciated.
