### ISSUE TITLE
[BUG]  'Cannot use 'in' operator to search for 'ver' in Timeout', name: 'TypeError'}​​​​​

### ISSUE THREAD

**Issue by MSNev** [microsoft/ApplicationInsights-JS#1656]
AI (Internal): 35 message:"trackException failed, exception will not be collected: TypeError" props:"{​​​​​exception:[object Error]{​​​​​ stack: 'TypeError: Cannot use 'in' operator to search for 'ver' in Timeout\n    at _isExceptionInternal (https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/vendors.chunk.js:5040:19)\n    at new Exception (https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/vendors.chunk.js:5074:14)\n    at ApplicationInsights._self.sendExceptionInternal (https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/vendors.chunk.js:6685:38)\n    at ApplicationInsights._self.trackException (https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/vendors.chunk.js:6700:27)\n    at Initialization.push.../../node_modules/@microsoft/applicationinsights-web/dist-esm/applicationinsights-web.js.Initialization.trackException (https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/vendors.chunk.js:10547:26)\n    at AppInsightsJSLogger.sendLog (https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/client.chunk.js:6978:18)\n    at https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/client.chunk.js:7225:77\n    at internal_telemetry_InternalTelemetry.notifyTraceLoggers (https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/client.chunk.js:7217:1)\n    at internal_telemetry_InternalTelemetry._log (https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/client.chunk.js:7225:42)\n    at internal_telemetry_InternalTelemetry.log (https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/client.chunk.js:7248:66)\n    at action_executor_ActionExecutor._actionWrapper (https://localhost:4000/_scnr/00000-00000-00000-00000-00000/static/js/client.chunk.js:355:261)', message: 'Cannot use 'in' operator to search for 'ver' in Timeout', name: 'TypeError'}​​​​​"

**Comment by MSNev** [comment]
v2.7.0 is not fully deployed to NPM and all CDN endpoints
