### ISSUE TITLE
[BUG] error thrown using basic version + NPM setup

### ISSUE THREAD

**Issue by lindsayevans** [microsoft/ApplicationInsights-JS#1875]
**Description/Screenshot**

I've installed the [basic version using NPM](https://github.com/microsoft/ApplicationInsights-JS#application-insights-web-basic), but attempting to initialise results in a JS error in the DevTools console:

```
index.js:34 Uncaught TypeError: _self.getSKUDefaults is not a function
    at index.js:34:1
    at dynamicProto (DynamicProto.js:514:1)
    at new ApplicationInsights (index.js:32:1)
    at jeorp.@microsoft/applicationinsights-web-basic (main.ts:3:21)
    at newRequire (index.b7a05eb9.js:71:24)
    at index.b7a05eb9.js:122:5
    at index.b7a05eb9.js:145:3
```

**Steps to Reproduce**

```sh
npm i --save @microsoft/applicationinsights-web-basic
```

```typescript
import { ApplicationInsights } from '@microsoft/applicationinsights-web-basic';

const appInsights = new ApplicationInsights({
  instrumentationKey: 'd999b489-4274-4a38-9526-0964fd808627',
});
```

Full code available here: https://github.com/lindsayevans/linz.id.au/tree/develop/src

Can be seen in action here: https://yellow-smoke-042698a1e-develop.westus2.1.azurestaticapps.net/

 - OS/Browser: macOS 10.15.7, Chrome 103
 - SDK Version [e.g. 22]: 2.8.6
 - How you initialized the SDK:

**Expected behavior**

**Additional context**

Checking the location from the error (node_modules/@microsoft/applicationinsights-web-basic/dist-esm/index.js:34:1), it looks like `getSKUDefaults` is called before being defined:

```js
_self.getSKUDefaults();
_initialize();
_self[_DYN_INITIALIZE /* @min:%2einitialize */] = _initialize;
_self.getSKUDefaults = function () {
```

Seems to be occurring with all 2.8.* versions, but works as expected with v2.7.6

```sh
npm i --save @microsoft/applicationinsights-web-basic@2.7.6
```

**Comment by lindsayevans** [comment]
FYI: just tested against the nightly build & everything looks good
