### ISSUE TITLE
ReferenceError: s is not defined

### ISSUE THREAD

**Issue by jonicabrown** [microsoft/ApplicationInsights-JS#708]
I'm getting the same error as closed issue #606 when implementing client-side app insights using the embedded JS script provided by MS (https://docs.microsoft.com/en-us/azure/application-insights/app-insights-javascript). In my code, I call the app insights event tracking, but nothing happens, including no telemetry and nothing in the console. When you step into the app insights JS you see that the code throws an exception but it's being caught and logged "internally" (not sure what that means - AppInsights.ts calling "_InternalLogging.throwInternal").

appInsights is definitely defined with valid instrumentation key; standard telemetry showing up in Azure Portal.

I pared down my request to bare minimum and still getting it:
appInsights.trackEvent("sendXitiPage");

Stack trace:
-------------
message: "s is not defined"
stack: "ReferenceError: s is not defined
at eval (eval at n.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:84831), <anonymous>:1:1)
at Object.n.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:84831)
at Object.module.sendXitiPage (http://localhost/utils/general.js:305:21)
at b.$scope.fetchMessage (http://localhost/Directive/curtain.js:23:37)
at controller (http://localhost/Directive/curtain.js:92:20)
at Object.invoke (http://localhost/ThirdParty/angular/angular.min.js:41:376)
at R.instance (http://localhost/ThirdParty/angular/angular.min.js:89:399)
at m (http://localhost/ThirdParty/angular/angular.min.js:65:65)
at http://localhost/ThirdParty/angular/angular.min.js:76:459
at http://localhost/ThirdParty/angular/angular.min.js:130:409"
__proto__: Error

![image](https://user-images.githubusercontent.com/36988370/46133366-93e8c080-c240-11e8-89e6-60b5a96d52a1.png)

_Originally posted by @jonicabrown in https://github.com/Microsoft/ApplicationInsights-JS/issues/606#issuecomment-425006890_

**Comment by jonicabrown** [comment]
Thanks Basel. The system this happens on is currently switched off; I'll do that when it's spun back up again.

**Comment by fredrik-lundin** [comment]
Hi,

I get exactly the same thing (except for me it says `i` instead of `s` is not defined) in my Angular SPA. The exact same used to work like a month ago, not it doesn't. I tried with this bare minimum code:
```typescript
AppInsights.downloadAndSetup({
      instrumentationKey: '154359d2-bf40-4253-b027-b0cd361efe51'
    });
AppInsights.trackEvent('TEST TEST');
```
And get this when I step into the debugger to inspect what's going on:
```
"ReferenceError: i is not defined
    at eval (eval at t.triggerSend (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:53092), <anonymous>:1:1)
    at t.triggerSend (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:53092)
    at https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:52357
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (https://localhost:5001/polyfills.js:6759:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (https://localhost:5001/polyfills.js:6526:47)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (https://localhost:5001/polyfills.js:6834:34)
    at ZoneTask.invoke (https://localhost:5001/polyfills.js:6823:48)
    at timer (https://localhost:5001/polyfills.js:8392:29)"
```

**Comment by fredrik-lundin** [comment]
Hi,

I get exactly the same thing (except for me it says `i` instead of `s` is not defined) in my Angular SPA. The exact same used to work like a month ago, not it doesn't. I tried with this bare minimum code:
```typescript
AppInsights.downloadAndSetup({
      instrumentationKey: '--my key--'
    });
AppInsights.trackEvent('TEST TEST');
```
And get this when I step into the debugger to inspect what's going on:
```
"ReferenceError: i is not defined
    at eval (eval at t.triggerSend (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:53092), <anonymous>:1:1)
    at t.triggerSend (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:53092)
    at https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:52357
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (https://localhost:5001/polyfills.js:6759:31)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (https://localhost:5001/polyfills.js:6526:47)
    at push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask (https://localhost:5001/polyfills.js:6834:34)
    at ZoneTask.invoke (https://localhost:5001/polyfills.js:6823:48)
    at timer (https://localhost:5001/polyfills.js:8392:29)"
```

**Comment by Votok** [comment]
I have the same problem. In Sender.ts even when the timeoutHandle has value, in debugger it somehow steps to the timerValue (last row) which is undefined...
I do not get why it is trying to step inside IF, when it should not.

`private _setupTimer() {
            if (!this._timeoutHandle) {
                var retryInterval = this._retryAt ? Math.max(0, this._retryAt - Date.now()) : 0;
                var timerValue = Math.max(this._config.maxBatchInterval(), retryInterval);

                this._timeoutHandle = setTimeout(() => {
                    this.triggerSend();
                }, timerValue);
            }
        }`

**Comment by AKomarinski** [comment]
Hello,
I am running into the same issue in my Angular app. Has anyone found a workaround or fix for this?

**Comment by markwolff** [comment]
Can you add this to your downloadAndSetup args and report back the new error stack? This just loads the nonminified SDK and turns on logging.
```ts
url: https://az416426.vo.msecnd.net/scripts/a/ai.js,
verboseLogging: true
```

**Comment by AKomarinski** [comment]
@markwolff I made those changes and it looks like I'm still getting minified references in my errors. Here is the error I get: 

```ReferenceError: s is not defined
    at eval (eval at n.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:84831), <anonymous>:1:1)
    at Object.n.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:84831)
    at CustomAppInsightsService.push../src/app/services/app-insights/app-insights.service.ts.CustomAppInsightsService.logEvent (http://localhost:4200/main.js:993:76)
    at SurveyDialogComponent.<anonymous> (http://localhost:4200/view-lead-view-lead-module.js:65707:42)
    at step (http://localhost:4200/view-lead-view-lead-module.js:65641:23)
    at Object.throw (http://localhost:4200/view-lead-view-lead-module.js:65622:53)
    at rejected (http://localhost:4200/view-lead-view-lead-module.js:65614:65)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.js:2726:26)
    at Object.onInvoke (http://localhost:4200/vendor.js:58831:33)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.js:2725:52)```

**Comment by markwolff** [comment]
Is caching enabled, or is it being downloaded somewhere else? It should be downloading `ai.js` at this point.

**Comment by AKomarinski** [comment]
cleared all my caching and opened the site in incognito mode and stil getting the same error as above. Just to provide some more context I am using the 'applicationinsights-js' node module and I am catching the error in the AppInsights.ts file located at /scripts/JavaScript/JavaScriptSDK/AppInsights.ts on my site. Here is the code I am reading from: 
```
            try {
                var eventTelemetry = new Telemetry.Event(name, properties, measurements);
                var data = new ApplicationInsights.Telemetry.Common.Data<ApplicationInsights.Telemetry.Event>(Telemetry.Event.dataType, eventTelemetry);
                var envelope = new Telemetry.Common.Envelope(data, Telemetry.Event.envelopeType);
                this.context.track(envelope);
            } catch (e) {
                _InternalLogging.throwInternal(LoggingSeverity.CRITICAL,
                    _InternalMessageId.TrackEventFailed,
                    "trackEvent failed, event will not be collected: " + Util.getExceptionName(e),
                    { exception: Util.dump(e) });
            }
```

**Comment by AKomarinski** [comment]
here is my download and setup, know there is some unnecessary stuff in here that I changed just to see if I could get my event to log. 
```
        AppInsights.downloadAndSetup({
            instrumentationKey: this.config.retrieveSetting('instrumentationKey'),
            samplingPercentage: 100,
            disableExceptionTracking: false,
            disableTelemetry: false,
            url: 'https://az416426.vo.msecnd.net/scripts/a/ai.js',
            verboseLogging: true
        });
```

**Comment by AKomarinski** [comment]
also worth noting: most of the events I am logging are appearing in my portal, but for some reason one particular event that I log from a component inside of angular material dialogue is not appearing. This error happens when I attempt to log that event.

**Comment by AKomarinski** [comment]
@markwolff here is some relevant stuff in my package.json if it helps
```
    "@angular/cdk": "^7.3.2",
    "@angular/material": "^7.3.2",
    "applicationinsights-js": "1.0.9",
    "zone.js": "~0.8.26"
    "typescript": "~3.1.6"
```

**Comment by markwolff** [comment]
@AKomarinski You can try using `1.0.20` of the SDK. This should let you grab the unminified version 😃 .

**Comment by AKomarinski** [comment]
@MarkPieszak rats! thought I had updated. However, after updating and clearing everything out I am still getting this 
```
ReferenceError: s is not defined
    at eval (eval at n.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:84831), <anonymous>:1:1)
    at Object.n.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:84831)
    at CustomAppInsightsService.push../src/app/services/app-insights/app-insights.service.ts.CustomAppInsightsService.logEvent (http://localhost:4200/main.js:994:76)
    at SurveyDialogComponent.<anonymous> (http://localhost:4200/view-lead-view-lead-module.js:65707:42)
    at step (http://localhost:4200/view-lead-view-lead-module.js:65641:23)
    at Object.throw (http://localhost:4200/view-lead-view-lead-module.js:65622:53)
    at rejected (http://localhost:4200/view-lead-view-lead-module.js:65614:65)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.js:2726:26)
    at Object.onInvoke (http://localhost:4200/vendor.js:58831:33)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (http://localhost:4200/polyfills.js:2725:52)
```

**Comment by AKomarinski** [comment]
@MarkPieszak we figured it out! One of the node modules we use was also doing a downloadAndSetup with a different telemetry key, which was overriding our apps instance. I think this also explains why we were never getting the unminified script after making the change you suggested. Thanks for the help and sorry for buggin you all on this.

**Comment by markwolff** [comment]
Good to hear. The multiple instance issue is fixed in the latest [beta version](https://github.com/Microsoft/ApplicationInsights-JS/tree/master/vNext/AISKU).

**Comment by MSNev** [comment]
Closing as this appear to be the legacy system that is no longer actively maintained and appears a workaround was identified
