### ISSUE TITLE
ReferenceError: define is not defined

### ISSUE THREAD

**Issue by CP-Ram** [Microsoft/ApplicationInsights-JS#749]
I have angular7 cli application and when building with @angular/platform-server using universal app-shell getting the following error on console.And i am using latest version 1.0.20 of applicationinsights-js.

**define is not defined
ReferenceError: define is not defined
    at Object.<anonymous> (D:\app2019\dev\myapp\customerapp\node_modules\applicationinsights-js\bundle\ai.module.js:215:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.applicationinsights-js (D:\app2019\dev\myapp\customerapp\wwwroot\my-universal-app-server\main.js:163971:18)
    at __webpack_require__ (D:\app2019\dev\myapp\customerapp\wwwroot\my-universal-app-server\main.js:20:30)
    at Module../ClientApp/app/components/common/app-insight/appinsight-service.ts (D:\app2019\dev\myapp\customerapp\wwwroot\my-universal-app-server\main.js:22454:80)
    at __webpack_require__ (D:\app2019\dev\myapp\customerapp\wwwroot\my-universal-app-server\main.js:20:30)
    at Module../ClientApp/app/components/globals/CommonService.ts (D:\app2019\dev\myapp\customerapp\wwwroot\my-universal-app-server\main.js:138091:96)
    at __webpack_require__ (D:\app2019\dev\myapp\customerapp\wwwroot\my-universal-app-server\main.js:20:30)
    at Module../ClientApp/app/components/template/app.component.ts (D:\app2019\dev\myapp\customerapp\wwwroot\my-universal-app-server\main.js:156278:80)
    at __webpack_require__**

And also tried with es2015 as module in tsconfig.server.json but it is not working.

**Comment by CP-Ram** [comment]
@markwolff, Please find the below Import  and download
![appinsightimport](https://user-images.githubusercontent.com/31565062/51071973-9bad6300-167f-11e9-98c7-968d840cd035.PNG)
And log event methods:
![logmethods](https://user-images.githubusercontent.com/31565062/51071978-b089f680-167f-11e9-9be3-2981f84b8030.PNG)

And the version in the package.json file:    
"applicationinsights-js": "^1.0.20",

**Comment by betterliyu** [comment]
We met the same issue. We use npm to manage this package. I think it is caused by ai.module.js under bundle folder.
![image](https://user-images.githubusercontent.com/19713797/51240398-91a89e80-19b6-11e9-9fae-0e9923ae362e.png)
Is it only support to load AppInsightsModule by AMD way?

**Comment by jpiyali** [comment]
The versions 1.0.x of the SDK only allow AMD consumers to work I believe. Version 2.0.x-beta (in beta currently) supports UMD (if you look in the npm package, we drop dists in the following formats):

/browser: intended to be used for browser (UMD)
/dist: intended for nodejs (commonjs format)
/ESM: future looking
/src: source code if you want to compile in your build system
