### ISSUE TITLE
sanitizeString: Object doesn't support property or method 'substring'

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-JS#98]
Trace:

AI (Internal): trackEvent failed, event will not be collected: [object Error]{ stack: 'TypeError: Object doesn't support property or method 'substring'
   at t.sanitizeString (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:36407)
   at t.sanitizeProperties (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:37600)
   at i (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:39361)
   at r.prototype.trackEvent (https://az416426.vo.msecnd.net/scripts/a/ai.0.js:1:64134)
   at Anonymous function (https://insightsportal-prod2-asiae-cdn.aisvc.visualstudio.com/Content/Dynamic/AmdBundleDefinition_5EFC510F9D2C40C634D27E76133BCC3FFF5D9E0F.js?root=**Shared/InsightsTelemetry:69:1)
   at apply (https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/UxFxStableScript_1EC6FDF61B57A560ED976C0A2202AC106FF13CDE.js:221:179)
   at f.promiseDispatch (https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/UxFxStableScript_1EC6FDF61B57A560ED976C0A2202AC106FF13CDE.js:219:875)
   at Anonymous function (https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/UxFxStableScript_1EC6FDF61B57A560ED976C0A2202AC106FF13CDE.js:227:45)
   at t (https://shell-s2-portal.azurecomcdn.net/Content/Dynamic/UxFxStableScript_1EC6FDF61B57A560ED976C0A2202AC106FF13CDE.js:223:201)', message: 'Object doesn't support property or method 'substring'', name: 'TypeError'

**Comment by AlexBulankou** [comment]
Fixed with #102
